NYSE = [
'A', 'AA', 'AACT', 'AAM', 'AAMI', 'AAP', 'AAUC', 'ABBV', 'ABCB', 'ABG',
'ABM', 'ABT', 'ACA', 'ACCO', 'ACEL', 'ACHR', 'ACI', 'ACM', 'ACN',
'ACVA', 'AD', 'ADCT', 'ADM', 'ADNT', 'ADT', 'AEE',
'AEM', 'AEO', 'AER', 'AES', 'AESI', 'AFG', 'AFL', 'AG', 'AGCO', 'AGI',
'AGL', 'AGO', 'AGRO', 'AGX', 'AI', 'AIG', 'AII', 'AIN', 'AIR', 'AIT',
'AIZ', 'AJG', 'AKA', 'AL', 'ALB', 'ALC', 'ALE', 'ALG', 'ALIT', 'ALK',
'ALL', 'ALLE', 'ALLY', 'ALSN', 'ALTG', 'ALUR', 'ALV', 'AM', 'AMBC',
'AMBP', 'AMC', 'AMCR', 'AME', 'AMG', 'AMN', 'AMP', 'AMPX', 'AMPY',
'AMR', 'AMRC', 'AMT', 'AMWL', 'AN', 'ANET', 'ANF', 'ANRO', 'ANVS',
'AON', 'AORT', 'AOS', 'AP', 'APAM', 'APD', 'APG', 'APH', 'APO', 'APTV',
'AR', 'ARCO', 'ARDT', 'ARES', 'ARIS', 'ARLO', 'ARMK', 'AROC', 'ARW',
'ARX', 'AS', 'ASAN', 'ASB', 'ASC', 'ASGN', 'ASH', 'ASIC', 'ASIX',
'ASPN', 'ATEN', 'ATGE', 'ATI', 'ATKR', 'ATMU', 'ATO', 'ATR', 'ATS',
'ATUS', 'AU', 'AUB', 'AUNA', 'AVA', 'AVBC', 'AVD', 'AVNS', 'AVNT',
'AVTR', 'AVY', 'AWI', 'AWK', 'AWR', 'AX', 'AXL', 'AXP', 'AXR', 'AXS',
'AXTA', 'AYI', 'AZO', 'AZZ', 'B', 'BA', 'BAC', 'BAH', 'BALL', 'BALY',
'BAM', 'BANC', 'BAP', 'BARK', 'BAX', 'BB', 'BBAI', 'BBDC',
'BBW', 'BBWI', 'BBY', 'BC', 'BCC', 'BCO', 'BDC', 'BDX', 'BE', 'BEN',
'BFAM', 'BFH', 'BFLY', 'BG', 'BGS', 'BGSF', 'BH', 'BHC', 'BHE', 'BHVN',
'BILL', 'BIO', 'BIRK', 'BJ', 'BK', 'BKE', 'BKH', 'BKSY', 'BKV',
'BLCO', 'BLD', 'BLDR', 'BLK', 'BLND', 'BLSH', 'BLX', 'BMI', 'BMO',
'BMY', 'BN', 'BNED', 'BOOT', 'BORR', 'BOW', 'BOX', 'BRBR', 'BRC',
'BRCC', 'BRK.B', 'BRO', 'BROS', 'BSX', 'BTE', 'BTU', 'BUR',
'BURL', 'BV', 'BW', 'BWA', 'BWMX', 'BWXT', 'BX', 'BXC', 'BY', 'BYD',
'BZH', 'C', 'CAAP', 'CABO', 'CACI', 'CADE', 'CAE', 'CAG', 'CAH', 'CAL',
'CALX', 'CARR', 'CARS', 'CAT', 'CATO', 'CAVA', 'CB', 'CBAN', 'CBNA',
'CBRE', 'CBT', 'CBZ', 'CC', 'CCJ', 'CCK', 'CCL', 'CCO', 'CCRD', 'CDE',
'CDP', 'CE', 'CF', 'CFG', 'CFR', 'CGAU', 'CHD', 'CHE', 'CHGG',
'CHH', 'CHPT', 'CHWY', 'CI', 'CIA', 'CIEN', 'CINT', 'CION', 'CIVI',
'CL', 'CLB', 'CLCO', 'CLF', 'CLH', 'CLS', 'CLVT', 'CLW', 'CLX', 'CM',
'CMA', 'CMBT', 'CMC', 'CMDB', 'CMG', 'CMI', 'CMP', 'CMS', 'CNA', 'CNC',
'CNK', 'CNM', 'CNMD', 'CNNE', 'CNO', 'CNP', 'CNS', 'CNX', 'COF',
'COHR', 'COMP', 'CON', 'COOK', 'COP', 'COR', 'COSO', 'COTY', 'COUR',
'CP', 'CPA', 'CPAY', 'CPF', 'CPK', 'CPNG', 'CPRI', 'CPS', 'CR', 'CRBG',
'CRC', 'CRCL', 'CRGY', 'CRH', 'CRI', 'CRK', 'CRL', 'CRM', 'CRS', 'CSL',
'CSTM', 'CSV', 'CSW', 'CTEV', 'CTO', 'CTOS', 'CTRA', 'CTRI', 'CTS',
'CTVA', 'CUBI', 'CURB', 'CURV', 'CVE', 'CVEO', 'CVI', 'CVLG', 'CVNA',
'CVS', 'CVX', 'CW', 'CWAN', 'CWH', 'CWK', 'CWT', 'CXM', 'CXT', 'CXW',
'CYD', 'D', 'DAC', 'DAL', 'DAN', 'DAR', 'DAY', 'DB', 'DBD', 'DBI',
'DCI', 'DCO', 'DD', 'DDD', 'DDS', 'DE', 'DEC', 'DECK', 'DELL', 'DFH',
'DFIN', 'DG', 'DGX', 'DHI', 'DHR', 'DHT', 'DHX', 'DIN', 'DINO', 'DIS',
'DK', 'DKS', 'DLB', 'DLX', 'DNA', 'DNOW', 'DOCN', 'DOCS', 'DOLE',
'DOUG', 'DOV', 'DOW', 'DRI', 'DSX', 'DT', 'DTE', 'DTM', 'DUK', 'DV',
'DVA', 'DVN', 'DX', 'DXC', 'DY', 'EAF', 'EAT', 'EB', 'EBF',
'EBS', 'ECG', 'ECL', 'ECO', 'ECVT', 'ED', 'EE', 'EEX', 'EFX', 'EFXT',
'EG', 'EGO', 'EGY', 'EHAB', 'EHC', 'EIG', 'EIX', 'EL', 'ELAN', 'ELF',
'ELV', 'EMA', 'EME', 'EMN', 'EMP', 'EMR', 'ENFY', 'ENOV', 'ENR', 'ENS',
'ENVA', 'EOG', 'EPAC', 'EPAM', 'EPC', 'EQBK', 'EQV', 'ERO', 'ES',
'ESAB', 'ESE', 'ESI', 'ESNT', 'ESTC', 'ETD', 'ETN', 'ETR', 'EVAC',
'EVC', 'EVEX', 'EVH', 'EVR', 'EVTC', 'EVTL', 'EW', 'EXK', 'EXP', 'EXPD',
'F', 'FAF', 'FBIN', 'FBK', 'FBP', 'FC', 'FCF', 'FCN', 'FCX', 'FDP',
'FDS', 'FDX', 'FE', 'FERG', 'FET', 'FF', 'FFWM', 'FG', 'FHI', 'FHN',
'FI', 'FICO', 'FIG', 'FIGS', 'FIHL', 'FIS', 'FIX', 'FLG', 'FLNG',
'FLO', 'FLOC', 'FLR', 'FLS', 'FLUT', 'FMC', 'FN', 'FNB', 'FND', 'FNF',
'FNV', 'FOA', 'FOR', 'FOUR', 'FPH', 'FRO', 'FSLY', 'FSM', 'FSS', 'FTI',
'FTK', 'FTS', 'FTV', 'FUBO', 'FUL', 'FUN', 'FVRR', 'G', 'GAP', 'GATX',
'GBCI', 'GBTG', 'GBX', 'GCI', 'GCO', 'GCTS', 'GD', 'GDDY', 'GDOT',
'GE', 'GENI', 'GES', 'GETY', 'GEV', 'GFF', 'GGG', 'GHC', 'GHLD', 'GHM',
'GIB', 'GIC', 'GIL', 'GIS', 'GKOS', 'GL', 'GLOB', 'GLW', 'GM', 'GME',
'GMED', 'GNE', 'GNK', 'GNRC', 'GNTY', 'GNW', 'GOLF', 'GOOS', 'GPC',
'GPI', 'GPK', 'GPN', 'GPOR', 'GPRK', 'GRBK', 'GRC', 'GRDN', 'GRMN',
'GRND', 'GRNT', 'GROV', 'GS', 'GTES', 'GTLS', 'GTN', 'GTY', 'GVA',
'GWH', 'GWRE', 'GWW', 'GXO', 'H', 'HAE', 'HAFN', 'HAL', 'HAYW', 'HBB',
'HBI', 'HBM', 'HCA', 'HCC', 'HCI', 'HD', 'HE', 'HEI', 'HG', 'HGTY',
'HGV', 'HI', 'HIG', 'HII', 'HIMS', 'HIPO', 'HL', 'HLF', 'HLI', 'HLIO',
'HLLY', 'HLT', 'HLX', 'HMN', 'HNGE', 'HNI', 'HOG', 'HOMB', 'HP',
'HPE', 'HPQ', 'HRB', 'HRI', 'HRL', 'HSY', 'HTH', 'HUBB', 'HUBS', 'HUM',
'HUN', 'HWM', 'HXL', 'HY', 'HZO', 'IAG', 'IBM', 'IBP', 'IBTA',
'ICE', 'ICL', 'IDA', 'IDT', 'IEX', 'IFF', 'IFS', 'IHS', 'IIIN', 'IMAX',
'INFA', 'INGM', 'INGR', 'INR', 'INSP', 'INSW', 'INVX', 'IONQ', 'IOT',
'IP', 'IPG', 'IPI', 'IQV', 'IR', 'IT', 'ITGR', 'ITT', 'ITW', 'IVZ',
'J', 'JACS', 'JBI', 'JBL', 'JBS', 'JBTM', 'JCI', 'JEF', 'JELD', 'JENA',
'JHG', 'JILL', 'JLL', 'JNJ', 'JOBY', 'JPM', 'JXN', 'K', 'KAI', 'KAR',
'KBDC', 'KBH', 'KBR', 'KD', 'KEN', 'KEX', 'KEY', 'KEYS', 'KFRC', 'KFS',
'KFY', 'KGC', 'KGS', 'KIM', 'KKR', 'KLC', 'KLG', 'KMI', 'KMPR', 'KMT',
'KMX', 'KN', 'KNF', 'KNSL', 'KNTK', 'KNX', 'KO', 'KODK', 'KOP', 'KORE',
'KOS', 'KR', 'KRO', 'KSS', 'KTB', 'KVUE', 'KVYO', 'KWR', 'L', 'LAC',
'LAD', 'LAW', 'LAZ', 'LB', 'LBRT', 'LC', 'LCII', 'LDI', 'LDOS', 'LEA',
'LEG', 'LEN', 'LEVI', 'LH', 'LHX', 'LII', 'LION', 'LLY', 'LMND', 'LMT',
'LNC', 'LNG', 'LNN', 'LOB', 'LOCL', 'LOW', 'LOAR', 'LSPD', 'LTC', 'LTH'
, 'LUMN', 'LUV', 'LVS', 'LVWR', 'LW', 'LXFR', 'LXU', 'LYB',
'LYV', 'LZB', 'M', 'MA', 'MAGN', 'MAN', 'MAS', 'MATV', 'MATX', 'MAX',
'MBC', 'MBI', 'MC', 'MCB', 'MCD', 'MCK', 'MCO', 'MCS', 'MCY', 'MD',
'MDT', 'MDU', 'MEC', 'MED', 'MEG', 'MEI', 'MET', 'MFC', 'MG', 'MGA',
'MGM', 'MGY', 'MHK', 'MHO', 'MIAX', 'MIR', 'MKC', 'MKL', 'MLI', 'MLM',
'MLNK', 'MLR', 'MMC', 'MMI', 'MMM', 'MMS', 'MNTN', 'MO', 'MOD', 'MODG',
'MOH', 'MOS', 'MOV', 'MP', 'MPC', 'MPX', 'MRC', 'MRK', 'MS', 'MSA',
'MSCI', 'MSDL', 'MSGE', 'MSGS', 'MSI', 'MSM', 'MT', 'MTAL', 'MTB',
'MTD', 'MTDR', 'MTG', 'MTH', 'MTN', 'MTRN', 'MTUS', 'MTW', 'MTX', 'MTZ',
'MUR', 'MUSA', 'MUX', 'MWA', 'MX', 'MYE', 'NABL', 'NAT', 'NBHC', 'NBR',
'NC', 'NCDL', 'NCLH', 'NE', 'NEE', 'NEM', 'NET', 'NEU', 'NEUE', 'NEXA',
'NFG', 'NGS', 'NGVC', 'NGVT', 'NI', 'NIC', 'NINE', 'NIQ', 'NJR', 'NKE',
'NL', 'NMG', 'NNI', 'NOA', 'NOC', 'NOG', 'NOMD', 'NOTE', 'NOV', 'NOW',
'NPB', 'NPK', 'NPO', 'NPWR', 'NRDY', 'NRG', 'NRGV', 'NSC', 'NSP', 'NTB',
'NTR', 'NU', 'NUE', 'NUS', 'NUVB', 'NVR', 'NVRI', 'NVST', 'NVT', 'NWN',
'NX', 'NXDR', 'NXE', 'NYT', 'O', 'OBK', 'OC', 'ODC', 'ODV', 'OEC',
'OFG', 'OGE', 'OGN', 'OGS', 'OI', 'OII', 'OIS', 'OKE', 'OKLO', 'OLN',
'OLO', 'OMC', 'OMF', 'OMI', 'ONIT', 'ONON', 'ONTF', 'ONTO', 'OOMA',
'OPAD', 'OPFI', 'OPY', 'OR', 'ORA', 'ORCL', 'ORI', 'ORN', 'OSCR', 'OSK',
'OTIS', 'OVV', 'OWLT', 'OXM', 'OXY', 'PAAS', 'PACK', 'PACS',
'PAG', 'PAGS', 'PAII', 'PAR', 'PARR', 'PATH', 'PAY', 'PAYC', 'PB',
'PBF', 'PBH', 'PBI', 'PCG', 'PCOR', 'PD', 'PDCC', 'PDS', 'PEG', 'PEN',
'PERF', 'PEW', 'PFE', 'PFGC', 'PFLT', 'PFS', 'PFSI', 'PG', 'PGR', 'PH',
'PHG', 'PHIN', 'PHM', 'PHR', 'PII', 'PINS', 'PIPR', 'PJT', 'PK', 'PKE',
'PKG', 'PL', 'PLNT', 'PLOW', 'PM', 'PNC', 'PNNT', 'PNR', 'PNW', 'POR',
'POST', 'PPG', 'PPL', 'PR', 'PRA', 'PRG', 'PRGO', 'PRI', 'PRIM', 'PRLB',
'PRM', 'PRO', 'PRU', 'PSFE', 'PSN', 'PSQH', 'PSTG', 'PSX', 'PUMP',
'PVH', 'PWR', 'PX', 'QBTS', 'QGEN', 'QS', 'QSR', 'QTWO', 'QUAD', 'QXO',
'R', 'RAC', 'RACE', 'RAL', 'RAMP', 'RBA', 'RBC', 'RBLX', 'RBOT', 'RC',
'RCL', 'RCUS', 'RDDT', 'RDN', 'RDW', 'RES', 'REVG', 'REX', 'REZI', 'RF',
'RFL', 'RGA', 'RGR', 'RH', 'RHI', 'RIG', 'RJF', 'RKT', 'RL', 'RLI',
'RM', 'RMD', 'RNG', 'RNGR', 'RNR', 'RNST', 'ROG', 'ROK', 'ROL', 'RPM',
'RRC', 'RRX', 'RS', 'RSG', 'RSI', 'RSKD', 'RTX', 'RVLV', 'RVTY', 'RXO',
'RYAN', 'RYI', 'S', 'SA', 'SAH', 'SAM', 'SAND', 'SAR', 'SBSI', 'SCCO',
'SCHW', 'SCI', 'SCL', 'SCM', 'SCS', 'SD', 'SEE', 'SEG', 'SEI', 'SEM',
'SEMR', 'SES', 'SF', 'SFBS', 'SFL', 'SG', 'SGHC', 'SGI', 'SHAK',
'SHCO', 'SHW', 'SI', 'SIG', 'SII', 'SITE', 'SJM', 'SKE', 'SKIL', 'SKLZ',
'SKX', 'SKY', 'SKYH', 'SLB', 'SLF', 'SLGN', 'SLQT', 'SLVM', 'SM', 'SMC',
'SMG', 'SMHI', 'SMP', 'SMR', 'SMRT', 'SMWB', 'SN', 'SNA', 'SNAP',
'SNDA', 'SNDR', 'SNOW', 'SNV', 'SNX', 'SO', 'SOC', 'SOLV', 'SON',
'SOS', 'SOUL', 'SPB', 'SPGI', 'SPIR', 'SPMC', 'SPOT', 'SPR',
'SPXC', 'SR', 'SRE', 'SRI', 'SSB', 'SSD', 'SST', 'SSTK', 'ST',
'STE', 'STEL', 'STEM', 'STLA', 'STM', 'STN', 'STNG', 'STT', 'STVN',
'STZ', 'SU', 'SUPV', 'SVV', 'SW', 'SWK', 'SWX', 'SXC', 'SXI', 'SXT',
'SYF', 'SYK', 'SYY', 'T', 'TAC', 'TALO', 'TAP', 'TBBB', 'TBI', 'TBN',
'TDC', 'TDG', 'TDOC', 'TDS', 'TDW', 'TDY', 'TE', 'TECK', 'TEL', 'TEN',
'TEX', 'TFC', 'TFII', 'TFIN', 'TFPM', 'TFX', 'TG', 'TGE', 'TGLS',
'TGNA', 'TGT', 'THC', 'THG', 'THO', 'THR', 'THS', 'TIC', 'TISI', 'TIXT',
'TJX', 'TK', 'TKO', 'TKR', 'TLYS', 'TMHC', 'TMO', 'TNC', 'TNET', 'TNK',
'TNL', 'TOL', 'TOST', 'TPB', 'TPC', 'TPH', 'TPR', 'TR', 'TRAK', 'TRC',
'TREX', 'TRGP', 'TRN', 'TROX', 'TRU', 'TRV', 'TSE', 'TSN', 'TSQ', 'TT',
'TTAM', 'TTC', 'TTI', 'TU', 'TWI', 'TWLO', 'TXNM', 'TXT', 'TYL',
'UAA', 'UBER', 'UDR', 'UFI', 'UGI', 'UHS', 'UI', 'UIS', 'ULS', 'UNF',
'UNM', 'UNP', 'UP', 'USB', 'USFD', 'USNA', 'USPH', 'UTI', 'UTZ', 'UVE',
'UVV', 'UWMC', 'V', 'VAC', 'VAL', 'VATE', 'VEEV', 'VEL', 'VET', 'VFC',
'VG', 'VHC', 'VHI', 'VIK', 'VIRT', 'VLN', 'VLO', 'VLTO', 'VMC', 'VMI',
'VNCE', 'VNT', 'VOYA', 'VOYG', 'VPG', 'VRT', 'VRTS', 'VSCO', 'VSH',
'VST', 'VSTS', 'VTEX', 'VTLE', 'VTOL', 'VTS', 'VVV', 'VVX', 'VYX', 'VZ',
'W', 'WAB', 'WAL', 'WAT', 'WBS', 'WBX', 'WCC', 'WCN', 'WEAV', 'WEC',
'WEX', 'WFC', 'WFG', 'WGO', 'WH', 'WHD', 'WHG', 'WHR', 'WK', 'WKC',
'WLK', 'WLY', 'WM', 'WMB', 'WMK', 'WMS', 'WMT', 'WNC', 'WNS', 'WOLF',
'WOR', 'WRB', 'WRBY', 'WS', 'WSM', 'WSO', 'WST', 'WT', 'WTI',
'WTM', 'WTRG', 'WTS', 'WTTR', 'WU', 'WWW', 'XHR', 'XOM', 'XPER', 'XPO',
'XPOF', 'XPRO', 'XYL', 'XYZ', 'YELP', 'YETI', 'YEXT', 'YOU', 'YUM',
'YUMC',
]

NASDAQ = [
    'AACI', 'AAL', 'AAME', 'AAOI', 'AAON', 'AAPL', 'ABAT', 'ABCL', 'ABL', 'ABNB', 
    'ABOS', 'ABSI', 'ABTC', 'ABTS', 'ABUS', 'ABVC', 'ACAD', 'ACDC', 'ACET', 'ACFN', 
    'ACGL', 'ACHC', 'ACHV', 'ACIU', 'ACIW', 'ACLS', 'ACLX', 'ACMR', 'ACNB', 
    'ACNT', 'ACON', 'ACRS', 'ACRV', 'ACT', 'ACTG', 'ACTU', 'ACXP', 'ADBE', 'ADEA', 
    'ADI', 'ADIL', 'ADMA', 'ADN', 'ADP', 'ADPT', 'ADSE', 'ADSK', 'ADTN', 'ADTX', 
    'ADUS', 'ADV', 'ADVM', 'AEHL', 'AEHR', 'AEIS', 'AEMD', 'AEVA', 'AEYE', 'AFBI', 
    'AFRM', 'AFYA', 'AGEN', 'AGH', 'AGIO', 'AGMH', 'AGRI', 'AGYS', 'AHCO', 'AIHS', 
    'AIMD', 'AIRG', 'AIRS', 'AIRT', 'AKAM', 'AKAN', 'AKBA', 'AKRO', 'ALAB', 'ALCO', 
    'ALDX', 'ALEC', 'ALGM', 'ALGN', 'ALGS', 'ALGT', 'ALHC', 'ALKS', 'ALKT', 'ALLO', 
    'ALLR', 'ALLT', 'ALNY', 'ALOT', 'ALRM', 'ALRS', 'ALT', 'ALTI', 'ALTO', 'ALVO', 
    'ALXO', 'ALZN', 'AMAL', 'AMAT', 'AMBA', 'AMCX', 'AMD', 'AMGN', 'AMKR', 'AMLX', 
    'AMPH', 'AMPL', 'AMRK', 'AMRX', 'AMSC', 'AMSF', 'AMST', 'AMTX', 'AMWD', 'AMZN', 
    'ANAB', 'ANDE', 'ANEB', 'ANGI', 'ANGO', 'ANIK', 'ANIP', 'ANIX', 'ANNX', 'ANY', 
    'AOSL', 'AOUT', 'APA', 'APDN', 'APEI', 'APGE', 'APLD', 'APLS', 'APLT', 'APM', 
    'APOG', 'APP', 'APPF', 'APPN', 'APPS', 'APRE', 'APVO', 'APWC', 'APYX', 'AQB', 
    'AQMS', 'AQST', 'ARAY', 'ARBE', 'ARCB', 'ARCT', 'ARDX', 'AREC', 'ARHS', 'ARKO', 
    'ARKR', 'AROW', 'ARQT', 'ARRY', 'ARTL', 'ARTNA', 'ARTW', 'ARVN', 'ARWR', 
    'ASLE', 'ASMB', 'ASNS', 'ASO', 'ASPI', 'ASPS', 'ASRT', 'ASRV', 'ASTC', 'ASTE', 
    'ASTI', 'ASTL', 'ASTS', 'ASUR', 'ASYS', 'ATAI', 'ATEC', 'ATER', 'ATEX', 'ATHA', 
    'ATLC', 'ATLO', 'ATLX', 'ATNI', 'ATOM', 'ATOS', 'ATRA', 'ATRC', 'ATRO', 'ATXS', 
    'ATYR', 'AUBN', 'AUDC', 'AUPH', 'AUR', 'AURA', 'AUUD', 'AVAH', 'AVAV', 'AVDL', 
    'AVDX', 'AVGO', 'AVIR', 'AVNW', 'AVO', 'AVPT', 'AVT', 'AVTX', 'AVXL', 'AWRE', 
    'AXGN', 'AXON', 'AXSM', 'AXTI', 'AYTU', 'AZTA', 'BAND', 'BANF', 'BANR', 'BASE', 
    'BBCP', 'BBIO', 'BBLG', 'BBSI', 'BCAB', 'BCBP', 'BCDA', 'BCML', 'BCPC', 'BCRX', 
    'BCTX', 'BDTX', 'BEAM', 'BEAT', 'BEEM', 'BELFB', 'BENF', 'BETR', 'BFIN', 'BFST', 
    'BGC', 'BGFV', 'BIIB', 'BIOX', 'BIRD', 'BITF', 'BIVI', 'BJDX', 'BJRI', 'BKNG', 
    'BKR', 'BL', 'BLBD', 'BLDP', 'BLFS', 'BLFY', 'BLKB', 'BLMN', 'BLNK', 'BLZE', 
    'BMBL', 'BMEA', 'BMRC', 'BMRN', 'BNGO', 'BNTC', 'BOKF', 'BOLT', 'BOOM', 
    'BOSC', 'BPOP', 'BRAG', 'BRID', 'BRKR', 'BRY', 'BRZE', 'BSET', 'BSGM', 'BSVN', 
    'BSY', 'BTAI', 'BTBT', 'BTCS', 'BTDR', 'BTMD', 'BUSE', 'BYND', 'BYRN', 'BYSI', 
    'BZFD', 'CAAS', 'CABA', 'CAC', 'CACC', 'CAKE', 'CALM', 'CAMT', 'CAPR', 'CARG', 
    'CARV', 'CASH', 'CASY', 'CATY', 'CBNK', 'CBRL', 'CBSH', 'CCB', 'CCBG', 'CCCC', 
    'CCCS', 'CCNE', 'CCOI', 'CCRN', 'CDIO', 'CDLX', 'CDNA', 'CDNS', 'CDTX', 'CDW', 
    'CDXS', 'CECO', 'CEG', 'CELH', 'CENTA', 'CENX', 'CERS', 'CERT', 'CEVA', 
    'CFBK', 'CFFI', 'CFFN', 'CFLT', 'CGEM', 'CGEN', 'CGNT', 'CGNX', 'CHCO', 'CHDN', 
    'CHEF', 'CHKP', 'CHMG', 'CHR', 'CHRD', 'CHRS', 'CHRW', 'CHTR', 'CIFR', 'CIGI', 
    'CINF', 'CING', 'CIVB', 'CLAR', 'CLBK', 'CLBT', 'CLDX', 'CLFD', 'CLMB', 'CLMT',
     'CLNE', 'CLNN', 'CLOV', 'CLPT', 'CLRB', 'CLRO', 'CLSD', 'CLSK', 'CLST', 
    'CMBM', 'CMCO', 'CMCSA', 'CME', 'CMPR', 'CMPX', 'CMTL', 'CNDT', 'CNFR', 'CNOB', 
    'CNSP', 'CNTB', 'CNTX', 'CNTY', 'CNXC', 'CNXN', 'COCO', 'COCP', 'CODA', 'CODX', 
    'COFS', 'COGT', 'COHU', 'COIN', 'COKE', 'COLB', 'COLL', 'COLM', 'COMM', 'COO', 
    'COOP', 'CORT', 'CORZ', 'COSM', 'COST', 'CPB', 'CPHC', 'CPIX', 'CPRT', 'CPRX', 
    'CPSH', 'CPSS', 'CRAI', 'CRBP', 'CRBU', 'CRCT', 'CRDF', 'CRDL', 'CRDO', 'CRIS', 
    'CRMD', 'CRML', 'CRMT', 'CRNC', 'CRNT', 'CRNX', 'CRON', 'CROX', 'CRSP', 'CRSR', 
    'CRUS', 'CRVL', 'CRVS', 'CRWD', 'CSBR', 'CSCO', 'CSGP', 'CSGS', 'CSIQ', 'CSTE', 
    'CSTL', 'CSWC', 'CSX', 'CTAS', 'CTKB', 'CTLP', 'CTMX', 'CTRN', 'CTSH', 'CTSO', 
    'CTXR', 'CUE', 'CURI', 'CVAC', 'CVBF', 'CVCO', 'CVGI', 'CVGW', 'CVLT', 'CVRX', 
    'CWCO', 'CWST', 'CXAI', 'CXDO', 'CYBR', 'CYCC', 'CYCN', 'CYN', 'CYRX', 'CYTK', 
    'CZFS', 'CZNC', 'CZR', 'DAIO', 'DAKT', 'DARE', 'DASH', 'DAVE', 'DAWN', 'DBX', 
    'DCBO', 'DCGO', 'DCTH', 'DDOG', 'DENN', 'DERM', 'DGICA', 'DGICB', 'DGII', 'DGLY', 
    'DGNX', 'DH', 'DHIL', 'DIBS', 'DIOD', 'DJCO', 'DJT', 'DKNG', 'DLHC', 'DLO', 
    'DLPN', 'DLTH', 'DLTR', 'DMRC', 'DNLI', 'DNUT', 'DOCU', 'DOGZ', 'DOMO', 'DOOO', 
    'DORM', 'DOX', 'DPRO', 'DPZ', 'DRCT', 'DRIO', 'DRMA', 'DRRX', 'DRS', 'DRUG', 
    'DRVN', 'DSGN', 'DSGX', 'DSP', 'DSWL', 'DVAX', 'DXCM', 'DXLG', 'DXPE', 'DYAI', 
    'DYN', 'EA', 'EBAY', 'EBC', 'ECBK', 'ECOR', 'ECPG', 'EDIT', 'EDUC', 'EEFT', 
    'EGBN', 'EGHT', 'EHTH', 'EKSO', 'ELBM', 'ELDN', 'ELSE', 'ELTK', 'ELUT', 'ELVN', 
    'EMBC', 'EML', 'ENLT', 'ENLV', 'ENPH', 'ENSG', 'ENTA', 'ENTG', 'ENVX', 'EOLS', 
    'EOSE', 'EPIX', 'EPRX', 'EPSN', 'ERAS', 'ERIE', 'ERII', 'ESCA', 'ESEA', 'ESGL', 
    'ESLT', 'ESPR', 'ESQ', 'ESTA', 'ETNB', 'ETON', 'ETSY', 'EVCM', 'EVER', 'EVGN', 
    'EVGO', 'EVOK', 'EVRG', 'EWBC', 'EWCZ', 'EXAS', 'EXC', 'EXEL', 'EXFY', 'EXLS', 
    'EXPE', 'EXPI', 'EXPO', 'EXTR', 'EYE', 'EYPT', 'FANG', 'FARM', 'FAST', 'FATE', 
    'FBIO', 'FBIZ', 'FBNC', 'FBRX', 'FCAP', 'FCEL', 'FCFS', 'FCNCA', 'FDBC', 'FDMT', 
    'FDUS', 'FEAM', 'FELE', 'FENC', 'FFBC', 'FFIC', 'FFIN', 'FFIV', 'FGBI', 'FGEN', 
    'FIBK', 'FINW', 'FISI', 'FITB', 'FIVE', 'FIVN', 'FIZZ', 'FLEX', 'FLGC', 'FLGT', 
    'FLL', 'FLNC', 'FLNT', 'FLUX', 'FLWS', 'FLXS', 'FLYW', 'FMAO', 'FMBH', 'FMNB', 
    'FOLD', 'FONR', 'FORD', 'FORM', 'FORR', 'FOSL', 'FOXA', 'FOXF', 'FPAY', 'FRAF', 
    'FRBA', 'FRD', 'FRGT', 'FRHC', 'FRME', 'FROG', 'FRPT', 'FRSH', 'FRST', 'FSBC', 
    'FSBW', 'FSEA', 'FSLR', 'FSTR', 'FSV', 'FTCI', 'FTDR', 'FTEK', 'FTNT', 'FTRK', 
    'FULC', 'FULT', 'FUSB', 'FVCB', 'FWONK', 'FWRD', 'FWRG', 'FXNC', 'FYBR',
     'GABC', 'GAIA', 'GAIN', 'GALT', 'GAMB', 'GAME', 'GANX', 'GASS', 'GBDC', 
    'GBIO', 'GCBC', 'GCT', 'GDEN', 'GDRX', 'GDYN', 'GEHC', 'GEN', 'GENK', 
    'GEOS', 'GERN', 'GEVO', 'GFAI', 'GFS', 'GH', 'GIFI', 'GIII', 'GILD', 
    'GILT', 'GLBE', 'GLBS', 'GLBZ', 'GLDD', 'GLMD', 'GLNG', 'GLSI', 'GLTO', 
    'GLUE', 'GMGI', 'GNLN', 'GNPX', 'GNSS', 'GNTX', 'GO', 'GOCO', 'GOGO', 
    'GOOGL', 'GORV', 'GOSS', 'GOVX', 'GPRE', 'GPRO', 'GRAN', 
    'GREE', 'GRPN', 'GRWG', 'GSAT', 'GSBC', 'GSHD', 'GSIT', 'GSM', 'GT', 
    'GTBP', 'GTEC', 'GTIM', 'GTLB', 'GTX', 'GURE', 'GV', 'GWRS', 'HAFC', 
    'HAIN', 'HALO', 'HAS', 'HBAN', 'HBCP', 'HBIO', 'HBNC', 'HBT', 'HCAT', 
    'HCKT', 'HCSG', 'HDSN', 'HELE', 'HFBL', 'HFFG', 'HFWA', 'HGBL', 'HHS', 
    'HIFS', 'HIHO', 'HLIT', 'HLMN', 'HLNE', 'HNNA', 'HNRG', 'HNST', 'HOFT', 
    'HOLX', 'HON', 'HOOD', 'HOPE', 'HOTH', 'HOUR', 'HOWL', 'HPK', 'HQI', 
    'HQY', 'HRMY', 'HROW', 'HRTX', 'HRZN', 'HSCS', 'HSDT', 'HSIC', 'HSII', 
    'HST', 'HSTM', 'HTBK', 'HTLD', 'HUBG', 'HUMA', 'HURC', 'HURN', 
    'HUT', 'HWBK', 'HWC', 'HWKN', 'HYFM', 'HYMC', 'IAC', 'IART', 'IAS', 
    'IBCP', 'IBEX', 'IBIO', 'IBKR', 'IBOC', 'ICCC', 'ICCM', 'ICFI', 'ICHR', 
    'ICLR', 'ICON', 'ICU', 'ICUI', 'IDCC', 'IDN', 'IDXX', 'IDYA', 'IESC', 
    'IFRX', 'IGIC', 'IHRT', 'III', 'IIIV', 'IINN', 'IKT', 'ILMN', 'IMCC', 
    'IMKTA', 'IMMR', 'IMMX', 'IMNM', 'IMRX', 'IMTX', 'IMUX', 'IMVT', 'IMXI', 
    'INAB', 'INBK', 'INBS', 'INBX', 'INCY', 'INDB', 'INDI', 'INDV', 'INGN', 
    'INKT', 'INM', 'INMB', 'INMD', 'INO', 'INOD', 'INSE', 'INSG', 
    'INSM', 'INTA', 'INTC', 'INTG', 'INTU', 'INV', 'INVA', 'INVE', 'INVZ', 
    'IONS', 'IOSP', 'IOVA', 'IPAR', 'IPDN', 'IPGP', 'IPSC', 'IPW', 'IPWR', 
    'IRBT', 'IRDM', 'IREN', 'IRIX', 'IRMD', 'IRON', 'IROQ', 'IRTC', 'IRWD', 
    'ISPC', 'ISRG', 'ISSC', 'ISTR', 'ITIC', 'ITRI', 'ITRN', 'IZEA', 'JACK', 
    'JAGX', 'JAKK', 'JAMF', 'JANX', 'JAZZ', 'JBHT', 'JBLU', 'JBSS', 'JCAP', 
    'JJSF', 'JKHY', 'JOUT', 'JRSH', 'JRVR', 'JSPR', 'JUNS', 'JVA', 'JYNT', 
    'KALA', 'KALU', 'KALV', 'KARO', 'KDP', 'KE', 'KELYB', 'KEQU', 
    'KFFB', 'KHC', 'KIDS', 'KINS', 'KLAC', 'KLIC', 'KLTR', 'KMB', 'KMDA', 
    'KNDI', 'KNSA', 'KOD', 'KOPN', 'KOSS', 'KPLT', 'KPRX', 'KPTI', 'KRMD', 
    'KRNT', 'KRNY', 'KROS', 'KRT', 'KRUS', 'KRYS', 'KTCC', 'KTOS', 'KURA', 
    'KVHI', 'KYMR', 'KZR', 'LAES', 'LAKE', 'LAMR', 'LARK', 'LASR', 'LAUR', 
    'LAZR', 'LBRDK', 'LCFY', 'LCID', 
    'LCNB', 'LCUT', 'LE', 'LECO', 'LEE', 'LEGH', 'LENZ', 'LESL', 'LFCR', 
    'LFMD', 'LFST', 'LFUS', 'LFVN', 'LGIH', 'LGND', 'LGVN', 'LICN', 'LIDR', 
    'LILAK', 'LIN', 'LINC', 'LIND', 'LITE', 'LIVE', 'LIVN', 'LKFN', 
    'LKQ', 'LMAT', 'LMB', 'LMNR', 'LNKB', 'LNSR', 'LNT', 'LNTH', 'LNW', 
    'LOAN', 'LOGI', 'LOOP', 'LOPE', 'LOVE', 'LPLA', 'LPRO', 'LPSN', 'LPTH', 
    'LPTX', 'LQDA', 'LQDT', 'LRCX', 'LRMR', 'LSBK', 'LSCC', 'LSTR', 'LTBR', 
    'LTRN', 'LTRX', 'LUCD', 'LULU', 'LUNG', 'LUNR', 'LVLU', 'LWAY', 'LWLG', 
    'LXRX', 'LYEL', 'LYFT', 'LYRA', 'LYTS', 'LZ', 'MAIA', 'MANH', 'MAPS', 'MAR', 'MARA', 'MASI', 'MASS', 'MAT', 'MATW', 
    'MAXN', 'MAYS', 'MBIN', 'MBIO', 'MBLY', 'MBOT', 'MBRX', 'MBUU', 'MBWM', 
    'MCBS', 'MCFT', 'MCHP', 'MCHX', 'MCRB', 'MCRI', 'MCW', 'MDB', 'MDLZ', 
    'MDWD', 'MDXG', 'MEDP', 'MEGL', 'MEIP', 'MELI', 'MEOH', 'MERC', 'MESA', 
    'META', 'METC', 'MGEE', 'MGIC', 'MGNI', 'MGNX', 'MGPI', 'MGRC', 'MGTX', 
    'MGYR', 'MIDD', 'MIGI', 'MIND', 'MIRM', 'MIST', 'MITK', 'MKSI', 'MKTW', 
    'MKTX', 'MLAB', 'MLKN', 'MLTX', 'MMSI', 'MMYT', 'MNDO', 'MNDY', 'MNKD', 
    'MNMD', 'MNOV', 'MNPR', 'MNRO', 'MNSB', 'MNST', 'MNTK', 'MNTS', 'MODD', 
    'MOFG', 'MORN', 'MOVE', 'MPAA', 'MPB', 'MPWR', 'MQ', 'MRAM', 'MRBK', 
    'MRCY', 'MRKR', 'MRNA', 'MRSN', 'MRTN', 'MRUS', 'MRVI', 'MRVL', 'MSBI', 
    'MSEX', 'MSFT', 'MSGM', 'MSTR', 'MTCH', 'MTRX', 'MTSI', 'MU', 'MVBF', 
    'MVIS', 'MVST', 'MXCT', 'MXL', 'MYFW', 'MYGN', 'MYRG', 'NAII', 'NATH', 
    'NATR', 'NAUT', 'NAVI', 'NBIX', 'NBTB', 'NCNO', 'NCRA', 'NDAQ', 'NDLS', 
    'NEO', 'NEOG', 'NETD', 'NFLX', 'NKTR', 'NKTX', 'NNBR', 'NNOX', 'NODK', 
    'NOVT', 'NRDS', 'NRIM', 'NRIX', 'NSIT', 'NSSC', 'NTAP', 'NTCT', 'NTGR', 
    'NTIC', 'NTLA', 'NTNX', 'NTRA', 'NTWK', 'NUTR', 'NVAX', 'NVCR', 'NVDA', 
    'NVEC', 'NVMI', 'NWBI', 'NWE', 'NWFL', 'NWL', 'NXPI', 'NXST', 'NXT', 
    'NYAX', 'NYXH', 'OABI', 'OCC', 'OCFC', 'OCUL', 'ODFL', 'ODP', 
    'OESX', 'OFIX', 'OFLX', 'OGI', 'OKTA', 'OLED', 'OLLI', 'OLPX', 'OM', 
    'OMCL', 'OMER', 'ON', 'ONB', 'ONCY', 'ONDS', 'ONEW', 'OPEN', 'OPBK', 
    'OPCH', 'OPK', 'OPRT', 'OPRX', 'ORGN', 'ORGO', 'ORIC', 'ORLY', 'ORMP', 
    'ORRF', 'OSBC', 'OSIS', 'OSPN', 'OSUR', 'OSW', 'OTEX', 'OTLK', 'OTTR', 
    'OUST', 'OVBC', 'OVID', 'OVLY', 'PACB', 'PAHC', 'PANW', 'PATK', 'PAX', 
    'PAYO', 'PAYS', 'PAYX', 'PBHC', 'PBPB', 'PBYI', 'PCAR', 'PCRX', 'PCTY', 
    'PDLB', 'PEBO', 'PEGA', 'PENN', 'PEP', 'PERI', 'PESI', 'PETS', 'PFBC', 
    'PFG', 'PFIS', 'PGC', 'PGEN', 'PGNY', 'PHAR', 'PHAT', 'PHUN', 'PHVS', 
    'PI', 'PINC', 'PKBK', 'PKOH', 'PLAB', 'PLAY', 'PLBY', 'PLCE', 'PLMR', 
    'PLRX', 'PLSE', 'PLTK', 'PLTR', 'PLUG', 'PLUS', 'PLXS', 'PMN', 'PMTS', 
    'PNFP', 'PNTG', 'PODD', 'POOL', 'POWI', 'POWL', 'POWW', 'PPC', 'PRAA', 
    'PRAX', 'PRCH', 'PRCT', 'PRDO', 'PRGS', 'PRLD', 'PRME', 'PROF', 'PROK', 
    'PROV', 'PRPH', 'PRPL', 'PRQR', 'PRSO', 'PRTA', 'PRTH', 'PRTS', 'PRVA', 
    'PSMT', 'PSNL', 'PTC', 'PTCT', 'PTEN', 'PTGX', 'PTLO', 'PTON', 'PUBM', 
    'PULM', 'PVBC', 'PYPL', 'PYXS', 'PZZA', 'QCOM', 'QCRH', 'QLYS', 'QMCO', 
    'QRVO', 'QSI', 'QTRX', 'QUIK', 'QURE', 'RAIL', 'RAIN', 'RAND', 'RAPT', 
    'RARE', 'RAVE', 'RBB', 'RBBN', 'RBCAA', 'RCAT', 'RCKT', 'RCKY', 'RCMT', 
    'RDNT', 'RDWR', 'REAL', 'REG', 'REGN', 'REKR', 'RELI', 'RELL', 'RELY', 
    'RENT', 'REPL', 'REYN', 'RFIL', 'RGEN', 'RGLD', 'RGNX', 'RGP', 'RGS', 
    'RICK', 'RIGL', 'RILY', 'RIOT', 'RIVN', 'RKLB', 'RLAY', 'RLMD', 'RLYB', 
    'RMBS', 'RMNI', 'RMR', 'RNA', 'ROCK', 'ROIV', 'ROKU', 'ROOT', 'ROP', 
    'ROST', 'RPAY', 'RPD', 'RPRX', 'RPTX', 'RRGB', 'RRR', 'RUN', 
    'RVMD', 'RVSB', 'RWAY', 'RXRX', 'RXST', 'RXT', 'RYTM', 'SABR', 'SABS', 
    'SAFT', 'SAIA', 'SAIC', 'SAIL', 'SAMG', 'SANA', 'SANM', 'SATS', 'SAVA', 
    'SBAC', 'SBCF', 'SBFG', 'SBFM', 'SBGI', 'SBLK', 'SBUX', 'SCHL', 'SCLX', 
    'SCOR', 'SCPH', 'SCSC', 'SCVL', 'SDGR', 'SEAT', 'SEDG', 'SEED', 'SEER', 
    'SEIC', 'SERA', 'SERV', 'SEZL', 'SFBC', 'SFIX', 'SFM', 
    'SFNC', 'SFST', 'SGA', 'SGC', 'SGHT', 'SGML', 'SGMO', 'SGRP', 'SGRY', 
    'SHBI', 'SHC', 'SHEN', 'SHIP', 'SHLS', 'SHOO', 'SHOP', 'SIBN', 'SIGA', 
    'SIGI', 'SILC', 'SIRI', 'SITM', 'SKIN', 'SKYW', 'SLAB', 'SLDB', 'SLDP', 
    'SLGL', 'SLM', 'SLNO', 'SLP', 'SLRC', 'SMBC', 'SMCI', 'SMID', 'SMMT', 
    'SMPL', 'SMSI', 'SMTC', 'SMTI', 'SNBR', 'SNCR', 'SNCY', 'SNDX', 'SNEX', 
    'SNPS', 'SNSE', 'SOFI', 'SONO', 'SOPA', 'SOUN', 'SPFI', 'SPNS', 'SPOK', 
    'SPRO', 'SPRY', 'SPSC', 'SPT', 'SPTN', 'SPWH', 'SPWR', 'SRAD', 'SRCE', 
    'SRDX', 'SRPT', 'SRRK', 'SRTS', 'SSNC', 'SSP', 'SSRM', 'SSYS', 'STAA', 
    'STBA', 'STEP', 'STGW', 'STKL', 'STLD', 'STNE', 'STOK', 'STRA', 'STRL', 
    'STRO', 'STRR', 'STRS', 'STRT', 'STTK', 'STX',
    'SUPN', 'SURG', 'SVA', 'SWBI', 'SWIM', 'SWKS', 'SYBT', 'SYBX', 'SYM', 
    'SYNA', 'SYPR', 'TACO', 'TACT', 'TALK', 'TARA', 'TARS', 'TASK', 'TATT', 
    'TBBK', 'TCBI', 'TCBK', 'TCMD', 'TCPC', 'TCRT', 'TCRX', 'TCX', 'TDUP', 
    'TEAM', 'TECH', 'TELA', 'TENB', 'TENX', 'TER', 'TERN', 'TFSL', 'TGTX', 
    'THFF', 'THRM', 'THRY', 'TIGO', 'TILE', 'TIPT', 'TITN', 'TLS', 'TLSA', 
    'TMC', 'TMDX', 'TMUS', 'TNDM', 'TNGX', 'TNXP', 'TNYA', 'TOWN', 'TPCS', 
    'TPG', 'TPST', 'TREE', 'TRIP', 'TRMB', 'TRMD', 'TRNS', 'TROW', 'TRS', 
    'TRUE', 'TRUP', 'TRVI', 'TSBK', 'TSCO', 'TSEM', 'TSHA', 'TSLA', 'TTD', 
    'TTEC', 'TTEK', 'TTGT', 'TTMI', 'TTWO', 'TURN', 'TUSK', 'TWIN', 'TWST', 
    'TXG', 'TXN', 'TXRH', 'TYRA', 'TZOO', 'UDMY', 'UEIC', 'UFPI', 'UFPT', 
    'UGRO', 'ULBI', 'ULCC', 'ULH', 'ULTA', 'UMBF', 'UNB', 'UNCY', 'URBN', 
    'URGN', 'USAU', 'USCB', 'USEG', 'USIO', 'UTMD', 'VALU', 'VBTX', 'VC', 
    'VCEL', 'VCTR', 'VCYT', 'VECO', 'VERA', 'VERI', 'VERU', 'VERX', 'VFF', 
    'VFS', 'VIAV', 'VICR', 'VINP', 'VIR', 'VIRC', 'VITL', 'VKTX', 'VLGEA', 
    'VLY', 'VMAR', 'VMD', 'VMEO', 'VNDA', 'VNOM', 'VOR', 'VRA', 'VRDN', 
    'VREX', 'VRM', 'VRNS', 'VRNT', 'VRRM', 'VRSK', 'VRSN', 'VRTX', 'VSAT', 
    'VSEC', 'VSTM', 'VTGN', 'VTRS', 'VTSI', 'VTVT', 'VTYX', 'VUZI', 'VYGR', 
    'WABC', 'WAFD', 'WALD', 'WATT', 'WBD', 'WDAY', 'WDC', 'WDFC', 'WEN', 
    'WERN', 'WEST', 'WEYS', 'WFRD', 'WHF', 'WILC', 'WINA', 'WING', 'WIX', 
    'WKHS', 'WLDN', 'WLFC', 'WMG', 'WOOF', 'WPRT', 'WRAP', 'WRLD', 'WSBC', 
    'WSBF', 'WSC', 'WSFS', 'WTBA', 'WTW', 'WULF', 'WVE', 'WW', 'WWD', 'WYNN', 
    'XAIR', 'XEL', 'XENE', 'XERS', 'XFOR', 'XGN', 'XMTR', 'XNCR', 'XOMA', 
    'XOS', 'XP', 'XPEL', 'XRAY', 'XRX', 'XXII', 'YMAB', 'YORW', 'YTRA', 
    'ZBRA', 'ZENV', 'ZETA', 'ZEUS', 'ZFOX', 'ZG', 'ZGN', 'ZIMV', 'ZION', 
    'ZIP', 'ZIVO', 'ZJYL', 'ZKIN', 'ZLAB', 'ZM', 'ZNTL', 'ZS', 'ZT', 
    'ZVRA', 'ZVSA', 'ZWS'
    ]