services:
  postgres:
    image: postgres:15
    container_name: airflow-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./airflow-postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost" ]
      interval: 5s
      timeout: 3s
      retries: 20

  airflow:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: airflow
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__WEB_SERVER_HOST: 0.0.0.0
      AIRFLOW__CORE__PARALLELISM: 4
      AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 2
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DATABASE_URL}

      PROJECT_ROOT: /opt/elt-canonical-data
      PYTHONPATH: /opt/elt-canonical-data/src

    volumes:
      - ../../airflow/dags:/opt/airflow/dags
      - ../../src:/opt/elt-canonical-data/src
      # - ../../airflow/logs:/opt/airflow/logs
      - ../../dbt:/opt/elt-canonical-data/dbt
      - ../../.dbt:/home/airflow/.dbt
      - ../../../elt-inference-models:/opt/elt-inference-models
      - ../../scripts:/opt/airflow/scripts

    ports:
      - "8080:8080"
      - "3838:3838"
      - "3839:3839"

    command: >
      bash -c "
        airflow db upgrade &&
        Rscript /opt/airflow/scripts/app.R > /opt/airflow/scripts/shiny.log 2>&1 &
        Rscript /opt/airflow/scripts/app_violin.R > /opt/airflow/scripts/shiny_violin.log 2>&1 &
        airflow webserver &
        airflow scheduler
      "
