version: 2

sources:
  - name: raw
    database: "{{ env_var('DB_DATABASE') }}"
    schema: raw
    tables:
      - name: api_data_ingestion_polygon
      - name: fib_seq
      - name: ticker_index_summary

  - name: cdm
    database: "{{ env_var('DB_DATABASE') }}"
    schema: cdm
    tables:
      - name: api_data_ingestion_massive
      - name: api_data_ingestion_yfinance

  - name: analysis
    database: "{{ env_var('DB_DATABASE') }}"
    schema: analysis
    tables:
      - name: ticker_cluster_segments
        meta:
          upstream_dbt_model: metrics.ticker_weighted_growth_ranking
