version: 2

sources:
  - name: raw
    database: "{{ env_var('DB_DATABASE', 'prod') }}"
    schema: raw
    tables:
      - name: fib_seq
      - name: ticker_index_summary
      - name: api_data_ingestion_massive
      - name: api_data_ingestion_massive_delisted
      - name: ticker_metadata

  - name: cdm
    database: "{{ env_var('DB_DATABASE', 'prod') }}"
    schema: cdm
    tables:
      - name: api_data_ingestion_yfinance
      - name: api_data_ingestion_massive

  - name: analysis
    database: "{{ env_var('DB_DATABASE', 'prod') }}"
    schema: analysis
    tables:
      - name: ticker_cluster_segments
        meta:
          upstream_dbt_model: metrics.ticker_weighted_growth_ranking
