# To run this script, execute the following from your terminal:
# Rscript plot_distributions.R
# This will generate a 'distributions.html' file in the directory where you run it.

# Load required library
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite", repos = "http://cran.us.r-project.org")
}
if (!requireNamespace("plotly", quietly = TRUE)) {
  install.packages("plotly", repos = "http://cran.us.r-project.org")
}
if (!requireNamespace("htmlwidgets", quietly = TRUE)) {
  install.packages("htmlwidgets", repos = "http://cran.us.r-project.org")
}
library(jsonlite)
library(plotly)
library(htmlwidgets)

# Load data from json generated by export_inference_data.py
file_path <- "data.json"
if (file.exists(file_path)) {
  df_json <- fromJSON(file_path)
  
  # Ensure the data frame is formatted correctly
  df <- data.frame(
    bucket = as.numeric(df_json$bucket),
    pct = as.numeric(df_json$pct),
    returns = as.numeric(df_json$returns),
    past_p05 = as.numeric(df_json$past_p05),
    past_p95 = as.numeric(df_json$past_p95),
    future_p05 = as.numeric(df_json$future_p05),
    future_p95 = as.numeric(df_json$future_p95)
  )
} else {
  stop("data.json not found! Please run export_inference_data.py first to generate the dataset.")
}

# Create an interactive box plot using custom statistics
fig <- plot_ly(df, x = ~bucket)

# Since we don't have true Q1/Q3, we'll use the p05, median, and p95 directly.
# By making q1=median and q3=median, the "box" flattens into a single median line,
# and the whiskers stretch to the 5th and 95th percentiles.

# Box plot for Past Alpha (P05/P95)
fig <- fig %>% add_boxplot(
  y = ~past_p05, # We must provide y even if we provide precomputed stats (ignored but required by r-plotly)
  lowerfence = ~past_p05,
  q1 = ~((past_p05 + past_p95)/2),
  median = ~((past_p05 + past_p95)/2),
  q3 = ~((past_p05 + past_p95)/2),
  upperfence = ~past_p95,
  name = 'Past Alpha (5th to 95th)',
  line = list(color = 'lightblue', width = 3),
  fillcolor = 'rgba(173, 216, 230, 0)', # Transparent box
  hovertemplate = "Bucket: %{x}<br>Past P95: %{upperfence}<br>Past P05: %{lowerfence}<extra></extra>"
)

# Box plot for Future Alpha (P05/P95)
fig <- fig %>% add_boxplot(
  y = ~returns, 
  lowerfence = ~future_p05,
  q1 = ~returns,
  median = ~returns,
  q3 = ~returns,
  upperfence = ~future_p95,
  name = 'Future Median & Range (5th to 95th)',
  line = list(color = 'firebrick', width = 3),
  fillcolor = 'rgba(178, 34, 34, 0)',
  hovertemplate = "Bucket: %{x}<br>Future P95: %{upperfence}<br>Median: %{median}<br>Future P05: %{lowerfence}<extra></extra>"
)

# Configure the layout and styling
fig <- fig %>% layout(
  title = "Past & Future Alpha Distribution by Z-Bucket",
  xaxis = list(
    title = "Past Alpha Z-Bucket",
    tickmode = "linear",
    dtick = 1
  ),
  yaxis = list(
    title = "Alpha vs Benchmark (%)",
    zeroline = TRUE,
    zerolinecolor = "gray"
  ),
  margin = list(l = 50, r = 50, b = 50, t = 50),
  showlegend = TRUE,
  boxmode = "group" # Group them side by side
)

# Save the interactive plot as an HTML file
saveWidget(fig, "distribution_analysis.html", selfcontained = TRUE)

cat("Interactive box plot successfully saved to 'distribution_analysis.html'\n")
