# To run this script, execute the following from your terminal:
# Rscript plot_returns.R
# This will generate a 'bucket_analysis.png' file in the directory where you run it.

# Load required library
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite", repos = "http://cran.us.r-project.org")
}
library(jsonlite)

# Load data from json generated by export_inference_data.py
file_path <- "data.json"
if (file.exists(file_path)) {
  df_json <- fromJSON(file_path)
  
  # Ensure the data frame is formatted correctly
  df <- data.frame(
    bucket = as.numeric(df_json$bucket),
    pct = as.numeric(df_json$pct),
    returns = as.numeric(df_json$returns)
  )
} else {
  stop("data.json not found! Please run export_inference_data.py first to generate the dataset.")
}

# Open a PNG file to save the plot
png("bucket_analysis.png", width=800, height=500)

# Set margins to allow for the second y-axis
par(mar = c(5, 4, 4, 4) + 0.3)  

# Plot the bar chart for Record Percentage (Left Axis)
barplot(df$pct, names.arg = df$bucket, col = "lightblue", 
        ylab = "Record Percentage per ID (%)", 
        xlab = "Past Excess Return Z-Bucket",
        main = "Excess Returns vs. Distribution by Z-Bucket",
        ylim = c(0, 45))

# Tell R we want to overlay the next plot
par(new = TRUE)

# Plot the line chart for Median Returns (Right Axis)
plot(df$bucket, df$returns, type = "b", pch = 16, col = "firebrick", lwd = 3,
     axes = FALSE, xlab = "", ylab = "", ylim = c(-5, 65))

# Add the Right Axis and its label
axis(side = 4, at = pretty(range(df$returns)))
mtext("Median Future Excess Return vs SPY (%)", side = 4, line = 3, col="firebrick")

# Close the file
dev.off()
