# To run this script, execute the following from your terminal:
# Rscript plot_returns.R
# This will generate a 'bucket_analysis.png' file in the directory where you run it.

# Load required library
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite", repos = "http://cran.us.r-project.org")
}
library(jsonlite)

# Load data from json generated by export_inference_data.py
file_path <- "data.json"
if (file.exists(file_path)) {
  df_json <- fromJSON(file_path)
  
  # Ensure the data frame is formatted correctly
  df <- data.frame(
    bucket = as.numeric(df_json$bucket),
    pct = as.numeric(df_json$pct),
    returns = as.numeric(df_json$returns)
  )
} else {
  stop("data.json not found! Please run export_inference_data.py first to generate the dataset.")
}

# To save the interactive plot, we need plotly and htmlwidgets
if (!requireNamespace("plotly", quietly = TRUE)) {
  install.packages("plotly", repos = "http://cran.us.r-project.org")
}
if (!requireNamespace("htmlwidgets", quietly = TRUE)) {
  install.packages("htmlwidgets", repos = "http://cran.us.r-project.org")
}
library(plotly)
library(htmlwidgets)

# Create the interactive dual-axis plot using plotly
fig <- plot_ly(df, x = ~bucket)

# Add the bar chart for Record Percentage (Left Axis)
fig <- fig %>% add_bars(y = ~pct, 
                        name = 'Record Percentage (%)', 
                        marker = list(color = 'lightblue'),
                        hovertemplate = "Bucket: %{x}<br>Percentage: %{y:.2f}%<extra></extra>")

# Add the line chart for Median Returns (Right Axis)
fig <- fig %>% add_lines(y = ~returns, 
                         name = 'Median Excess Return (%)', 
                         yaxis = 'y2',
                         line = list(color = 'firebrick', width = 3), 
                         marker = list(color = 'firebrick', size = 8),
                         hovertemplate = "Bucket: %{x}<br>Return: %{y:.2f}%<extra></extra>")

# Configure the dual-axis layout and styling
fig <- fig %>% layout(
  title = "Excess Returns vs. Distribution by Z-Bucket",
  xaxis = list(
    title = "Past Excess Return Z-Bucket",
    tickmode = "linear",
    dtick = 1
  ),
  yaxis = list(
    title = "Record Percentage per ID (%)", 
    range = c(0, max(df$pct) * 1.2)
  ),
  yaxis2 = list(
    title = "Median Future Excess Return vs SPY (%)",
    tickfont = list(color = "firebrick"),
    titlefont = list(color = "firebrick"),
    overlaying = "y",
    side = "right",
    range = c(min(df$returns) - 5, max(df$returns) + 5)
  ),
  margin = list(l = 50, r = 60, b = 50, t = 50),
  showlegend = TRUE,
  hovermode = "x unified" # Shows both values when hovering over a bucket
)

# Save the interactive plot as an HTML file
saveWidget(fig, "bucket_analysis.html", selfcontained = TRUE)

cat("Interactive plot successfully saved to 'bucket_analysis.html'\n")
